### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jtpio** [jtpio/p5-notebook#54]
Here are a couple of items for the p5 notebook roadmap. 

Some of them actually apply to a wider scope than just p5, and would define the building blocks for more generic in-browser jupyter kernels.

The idea is to start with the special case of the p5 notebook with multiple notebooks, and make it more generic afterwards.
---

- [ ] Add a pyp5js kernel backed by pyodide: #52 
- [ ] Improve kernel management (#7)
- [ ] Define a public interface to register kernels 
- [ ] Save notebooks to local storage: #20 
- [ ] Add a simple file browser to create, save and re-open existing notebooks
- [ ] Consolidate the jupyterlab server to it's functional for most of the use cases (but it doesn't have to be feature complete)
- [ ] Make the jupyterlab server pluggable using the same lab / lumino plugin system:
  - So users could replace some of the plugins, for example the contents manager
  - For example instead of writing to local storage this could be talking to external services using API calls
- [ ] Split up the components and switch to a monorepo structure
- [ ] Move some of the components to a separate repo
- [ ] p5 notebook should only be a distribution:
  - depending on the jupyterlab server in the browser
  - shipping with a predefined set of kernels
  - with its own minimal notebook UI (logo + p5 touch)
- [x] Add a splash screen: #23 
- [ ] Publish to npm: #27

**Comment by jtpio** [comment]
Most of the items mentioned above have actually been addressed by JupyterLite: https://github.com/jupyterlite/jupyterlite/
